### ISSUE TITLE
Enforce authentication

### ISSUE THREAD

**Issue by Jishrocks** [apify/proxy-chain#111] opened 2021-02-13 12:00 UTC
Yeah, as proxy-authorization headers ain't requested from the client, they ain't being sent and therefore the username and password comes as null.

I'm currently requiring them manually on prepareRequestFunction,
```js
if (!request.headers['proxy-authorization']) {
    request.socket.write([
        'HTTP/1.1 407 Proxy Authentication Required',
        'Proxy-Authenticate: Basic realm="proxy"',
        'Proxy-Connection: close',
    ].join('\r\n'))
    request.socket.end('\r\n\r\n')  // empty body
    return
}
 ```
Would love to see this fixed.
Thanks!

**Comment by jancurn** [comment] 2021-02-13 12:05
Isn't this a standard and expected behavior? The client needs to send `proxy-authorization` header, and if not, they get an error.

**Comment by Jishrocks** [comment] 2021-02-13 12:07
Most extensions, browsers, don't send by default. Even the most famous extension on chrome for proxies, SwitchyOmega requires a proxy-authenticate header.

**Comment by jancurn** [comment] 2021-02-13 12:10
But this is exactly what is done - see https://github.com/apify/proxy-chain/blob/master/src/server.js#L401

Please can you be more specific what is the problem? What is the current behavior?

**Comment by Jishrocks** [comment] 2021-02-13 12:13
I'm talking about clients connecting to ProxyChain server, not ProxyChain connecting to upstream...
Currently, proxy-chain server doesn't send a 407 Proxy Authentication Required status code when proxy-authorization header ain't present.

**Comment by jancurn** [comment] 2021-02-13 12:40
If you set `requestAuthentication: true` in your implementation of `prepareRequestFunction()`, then the server will send the `Proxy-Authenticate` header back to client. You're fully in control of this behavior.

**Comment by Jishrocks** [comment] 2021-02-13 12:53
But afaik upstream doesn't work with `requestAuthentication: true`

**Comment by jancurn** [comment] 2021-02-13 13:49
requestAuthentication is only use with respect to client connecting to
ProxyChain server, the upstream authentication is done automatically
depending on the upstreamProxyUrl that you provided in the prepare function.

(I’m writing from mobile)

**Comment by jancurn** [comment] 2021-02-15 13:42
Closing this for now, as it's not a bug

**Closed by jancurn** 2021-02-15 13:42 UTC
