### ISSUE TITLE
Proxy not updated and request not intercepted 

### ISSUE THREAD

**Issue by NesDev** [apify/proxy-chain#100] opened 2021-01-07 13:23 UTC
Hi,

I use more than 100 proxy-chain servers on 100 different ports on the same machine and for each proxy-chain server I often change the output proxy. But sometimes a proxy-chain server stop to intercept request and i can't change the output proxy but the requests continue to be sent on the old proxy and the proxy-chain server stop to send this type of log :
ProxyServer[30442]: 69 | !!! Handling CONNECT  xxxxxxx.com:443 HTTP/1.1
ProxyServer[30442]: 69 | Using upstream proxy http://xxxxx:xxxxx/

if i stop to send request on this proxy-chain server for few minutes the next request is intercepted and i can change the out proxy.

**Comment by jancurn** [comment] 2021-02-15 13:50
Couldn't this be caused by HTTPS connections lingering for a longer time? For performance reasons, web browsers keep TLS connections open for a few minutes and pass multiple requests through them

**Comment by NesDev** [comment] 2021-02-23 11:42
Yeah, I think you're right, but is there no way to turn it off?

**Comment by jancurn** [comment] 2021-02-23 11:52
I'm sure browsers have some internal setting for this, but this is out of scope for proxy-chain... closing this for now

**Closed by jancurn** 2021-02-23 11:52 UTC
