### ISSUE TITLE
Support for passwords having ":" in upstream proxies

### ISSUE THREAD

**Issue by Jishrocks** [apify/proxy-chain#108] opened 2021-02-12 12:27 UTC
I'm currently using proxyland.io, they're using : in password to separate sessions
the https-proxy-agent module supports : in passwords,
would be really glad if this request is possible

**Comment by jancurn** [comment] 2021-02-12 13:20
Note that we're using the official Node.js' `URL` class for parsing the URLs (added in https://github.com/apify/proxy-chain/pull/103), so if it doesn't support the ":" char in password, I'm afraid it would be difficult to add this

**Comment by jancurn** [comment] 2021-02-12 13:25
For some reason, the URL object escapes the `:`...

<img width="767" alt="Screen Shot 2021-02-12 at 14 25 16" src="https://user-images.githubusercontent.com/10612996/107773565-228d0800-6d3e-11eb-848a-c4fd927a6626.png">

**Comment by Jishrocks** [comment] 2021-02-12 13:35
Hey, can't you replace %3A with : on href and password?

**Comment by mnmkng** [comment] 2021-02-12 18:28
A related problem. In a proxy URL such as this:

```
http://user:p%40ssword@proxy.com:8000
```

The password is not decoded somewhere down the line, which causes socket close errors.

[RFC 1738](https://www.ietf.org/rfc/rfc1738.txt) confirms that it's correct to encode those characters in section 3.1:

> The user name (and password), if present, are followed by a commercial at-sign "@". Within the user and password field, any ":", "@", or "/" must be encoded.
   
So, we must make sure the user and password fields are properly decoded before they're used elsewhere (such as in the Authentication header).

**Comment by mnmkng** [comment] 2021-02-12 18:44
Ok, [RFC 3986](http://www.faqs.org/rfcs/rfc3986.html) is quite clear in section 3.2.1 that usernames and passwords can have any percent encoded characters, so I think we can safely decode them, because it is the expected behavior.

**Comment by jancurn** [comment] 2021-02-12 23:32
Fixed in https://github.com/apify/proxy-chain/pull/110, will release soon

**Comment by mnmkng** [comment] 2021-02-26 07:50
Fixed in #110

**Closed by mnmkng** 2021-02-26 07:50 UTC
