### ISSUE TITLE
A lot of TCP connections

### ISSUE THREAD

**Issue by Rumatoid** [apify/proxy-chain#362] opened 2022-12-06 19:41 UTC
proxy-chain generate a lot of TCP connections
without PC I have about 50 connections, but 150 with PC

Im using ProxyChain.Server with prepareRequestFunction

**Comment by kami4ka** [comment] 2022-12-16 21:59
Up! I Found the same issue. Connections are not closing.

**Comment by jirimoravcik** [comment] 2022-12-17 12:27
Hello guys,
thanks for reporting this issue. You have any minimal code to reproduce the problem?
Thanks

**Comment by Rumatoid** [comment] 2022-12-17 13:12
> Hello guys, thanks for reporting this issue. You have any minimal code to reproduce the problem? Thanks

Just use prepareRequestFunction and watch for TCP connections (in Linux for example)

**Comment by kami4ka** [comment] 2022-12-17 13:19
I suppose that the reason is that `timeout` event from the socket is not handled, so the connection wouldn't be closed, as in case of timeout it should be closed manually.

**Comment by jirimoravcik** [comment] 2023-02-22 09:12
Hello guys,
thanks for your effort to report this issue.
We have released version 2.2.1 that should not leak TCP connections anymore.

**Closed by jirimoravcik** 2023-02-22 09:12 UTC
Labels: t-platform
